# 开发环境配置(配置项只包括环境不同项)
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/system_b?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
    activemq:
      user: admin
      password: admin
      broker-url: tcp://127.0.0.1:61616
      in-memory: true
      #配置序列化信任所有的包
      packages:
        trust-all: true

logging:
  level:
    org.springframework:
      data: DEBUG
      web: DEBUG
    tk.mybatis: DEBUG


